name: Build and Release sing-box

permissions:
  contents: write

env:
  LINUX: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOAMD64=v1
  LINUX_CGO: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 GOAMD64=v1
  WINDOWS: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOAMD64=v1
  WINDOWS_CGO: CGO_ENABLED=1 GOOS=windows GOARCH=amd64 GOAMD64=v1
  TAG_DEFAULT: with_gvisor,with_reality_server,with_quic,with_utls,with_ech,with_dhcp,with_wireguard,with_acme,with_clash_api
  TAG_ALL: with_gvisor,with_reality_server,with_quic,with_utls,with_ech,with_dhcp,with_wireguard,with_acme,with_clash_api,with_v2ray_api,with_grpc

on:
  workflow_dispatch:
    inputs:
      sing_version:
        description: "sing-box version to build (e.g., v1.11.4)"
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.23
        cache: false

    - name: git clone
      run: |
        git clone -b ${{ github.event.inputs.sing_version }} https://github.com/SagerNet/sing-box

    - name: Build Linux with default tag
      run: |
        cd sing-box
        go env -w ${{ env.LINUX }}
        go build -tags ${{ env.TAG_DEFAULT }} -v -o sing-box-linux -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ github.event.inputs.sing_version  }}' -s -w -buildid=" ./cmd/sing-box
        cd ..

    - name: Build Linux CGO with default tag
      run: |
        cd sing-box
        go env -w ${{ env.LINUX_CGO }}
        go build -tags ${{ env.TAG_DEFAULT }}-v -o sing-box-linux-CGO -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ github.event.inputs.sing_version  }}' -s -w -buildid=" ./cmd/sing-box
        cd ..

    - name: Build Linux with all tag
      run: |
        cd sing-box
        go env -w ${{ env.LINUX }}
        go build -tags ${{ env.TAG_ALL }} -v -o sing-box-linux-all -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ github.event.inputs.sing_version  }}' -s -w -buildid=" ./cmd/sing-box
        cd ..

    - name: Build Linux CGO with all tag
      run: |
        cd sing-box
        go env -w ${{ env.LINUX_CGO }}
        go build -tags ${{ env.TAG_ALL }}-v -o sing-box-linux-CGO-all -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ github.event.inputs.sing_version  }}' -s -w -buildid=" ./cmd/sing-box
        cd ..

    - name: Build Windows with default tag
      run: |
        cd sing-box
        go env -w ${{ env.WINDOWS }}
        go build -tags ${{ env.TAG_DEFAULT }} -v -o sing-box-windows.exe -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ github.event.inputs.sing_version  }}' -s -w -buildid=" ./cmd/sing-box
        cd ..

    - name: Build Windows CGO with default tag
      run: |
        cd sing-box
        go env -w ${{ env.WINDOWS_CGO }}
        go build -tags ${{ env.TAG_DEFAULT }}-v -o sing-box-windows-CGO.exe -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ github.event.inputs.sing_version  }}' -s -w -buildid=" ./cmd/sing-box
        cd ..

    - name: Build Windows with all tag
      run: |
        cd sing-box
        go env -w ${{ env.WINDOWS }}
        go build -tags ${{ env.TAG_ALL }} -v -o sing-box-windows-all.exe -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ github.event.inputs.sing_version  }}' -s -w -buildid=" ./cmd/sing-box
        cd ..

    - name: Build Windows CGO with all tag
      run: |
        cd sing-box
        go env -w ${{ env.WINDOWS_CGO }}
        go build -tags ${{ env.TAG_ALL }}-v -o sing-box-windows-CGO-all.exe -trimpath -ldflags "-X 'github.com/sagernet/sing-box/constant.Version=${{ github.event.inputs.sing_version  }}' -s -w -buildid=" ./cmd/sing-box
        cd ..

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: sing-box
        path: |
          sing-box-linux
          sing-box-linux-CGO
          sing-box-linux-all
          sing-box-linux-CGO-all
          sing-box-windows.exe
          sing-box-windows-CGO.exe
          sing-box-windows-all.exe
          sing-box-windows-CGO-all.exe

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.sing_version }}-build
        name: sing-box ${{ github.event.inputs.sing_version }} Build
        draft: false
        prerelease: false
        files: |
          sing-box-linux
          sing-box-linux-CGO
          sing-box-linux-all
          sing-box-linux-CGO-all
          sing-box-windows.exe
          sing-box-windows-CGO.exe
          sing-box-windows-all.exe
          sing-box-windows-CGO-all.exe
